# Generated by Django 5.0.7 on 2024-07-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albun',
            fields=[
                ('id_album', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('anio', models.DateField()),
            ],
            options={
                'db_table': 'album',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artisan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cantante', models.BooleanField(default=False)),
                ('instrumento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'artista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artista_Grupo',
            fields=[
                ('id_artista_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('creacion_registro', models.DateTimeField(auto_now_add=True)),
                ('agregado_por', models.DateField()),
            ],
            options={
                'db_table': 'artista_grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grupo',
                'managed': False,
            },
        ),
    ]
